### ISSUE TITLE
Fix length arrays of pointers is not supported.

### ISSUE THREAD

**Issue by kthompson** [kthompson/cxxi#2]
The generator does not properly handle the _Protseq_ field of the following struct:

``` C
 typedef struct _RPC_PROTSEQ_VECTORW {
 unsigned int Count;
 unsigned short * Protseq[1];
} RPC_PROTSEQ_VECTORW;
```

**Comment by stbrowne** [comment]
This has been fixed now. I'm not sure if there's a better way to handle it but any array of pointers is now treated as an IntPtr[]. I can't think a better way to handle this and maintain the original pointer types. If there is a way then we should probably do that, but for now this should be good enough.
