### ISSUE TITLE
Binding to LevelDB generates invalid code (halp!)

### ISSUE THREAD

**Issue by anaisbetts** [kthompson/cxxi#6]
So, I'm trying to bind [LevelDb](http://code.google.com/p/leveldb) via CXXI - I built GCC-XML and LevelDb from scratch, and ended up with an XML description (http://cl.ly/250O2r3s2T1D0519391x).  Executing generator.exe generates a set of C# files (http://cl.ly/1H453w2n2U2O2Q1Y0y1m), but those files don't compile.

I realize this is the most vague description ever, but if you've got any hints on how to debug / make fixes it'd be much appreciated.

**Comment by stbrowne** [comment]
Unfortunately I don't have a good answer for you without delving deeper into that specific library to see what is required and what is not. The problem you're seeing is that cxxi just tries to generate code for _EVERYTHING_ output by gccxml, but not all of what gccxml generates is actually required. You can actually specify filters to help you out with things like this. See the qt-gui-filters.xml file for an example. You'll probably just want to use those filters to generate ONLY the classes you plan on using.

Basically what I'm saying is right now there's a decent amount of manual effort into getting each and every specific library working. With a bit of work I can probably get all the generated output to be compilable, but even then I don't know that its all going to work right. I can guarantee that most of the generated code won't even be necessary though.

Ideally we need a GUI interface that would read the gccxml output and let you check/uncheck classes/namespaces that you want to include/exclude. It might be nice to even allow it on a per method basis in some cases too.

**Comment by stbrowne** [comment]
Just as a quick test I threw your output files in a project and started removing a number of files that weren't necessary, __, allocator_, et al. After getting rid of most of the generated crap that isn't necessary all you get left with are a few std::string (std::basic_string<>) references. I haven't tested std::string with cxxi so I don't know how well it would work if the generated output worked, but assuming you don't need those functions it should work. That's definitely one thing I've been meaning to look into though. Maybe I'll give that a shot soon.
